name: croniter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        set -ex
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    - name: Test with pytest
      run: |
           pyver=$(python --version 2>&1 | awk '{print substr($2, 0, 3)}');
           case $pyver in
             2.7) tox -e "py${pyver//\.}-{std,coverage}";;
             *) tox -e "py${pyver//\.}-std";;
           esac
